/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DailyStats = IDL.Record({
  'totalToiletPaperRolls' : IDL.Nat,
  'avgWipesPerPoop' : IDL.Float64,
  'totalPoops' : IDL.Nat,
  'totalWipes' : IDL.Nat,
});
export const Profile = IDL.Record({
  'background' : IDL.Text,
  'displayName' : IDL.Text,
  'color' : IDL.Text,
  'emoji' : IDL.Text,
});
export const Time = IDL.Int;
export const Entry = IDL.Record({
  'numberOfWipes' : IDL.Nat,
  'timestamp' : Time,
});
export const UserStats = IDL.Record({
  'principal' : IDL.Principal,
  'entries' : IDL.Vec(Entry),
  'totalToiletPaperRolls' : IDL.Nat,
  'avgWipesPerPoop' : IDL.Nat64,
  'totalPoops' : IDL.Nat,
  'totalWipes' : IDL.Nat64,
  'profile' : Profile,
});

export const idlService = IDL.Service({
  'createPoopEntry' : IDL.Func([IDL.Nat], [], []),
  'getDailyStats' : IDL.Func([], [DailyStats], ['query']),
  'getMyProfile' : IDL.Func([], [Profile], ['query']),
  'getRankedUserStats' : IDL.Func([], [IDL.Vec(UserStats)], ['query']),
  'register' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DailyStats = IDL.Record({
    'totalToiletPaperRolls' : IDL.Nat,
    'avgWipesPerPoop' : IDL.Float64,
    'totalPoops' : IDL.Nat,
    'totalWipes' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'background' : IDL.Text,
    'displayName' : IDL.Text,
    'color' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const Time = IDL.Int;
  const Entry = IDL.Record({ 'numberOfWipes' : IDL.Nat, 'timestamp' : Time });
  const UserStats = IDL.Record({
    'principal' : IDL.Principal,
    'entries' : IDL.Vec(Entry),
    'totalToiletPaperRolls' : IDL.Nat,
    'avgWipesPerPoop' : IDL.Nat64,
    'totalPoops' : IDL.Nat,
    'totalWipes' : IDL.Nat64,
    'profile' : Profile,
  });
  
  return IDL.Service({
    'createPoopEntry' : IDL.Func([IDL.Nat], [], []),
    'getDailyStats' : IDL.Func([], [DailyStats], ['query']),
    'getMyProfile' : IDL.Func([], [Profile], ['query']),
    'getRankedUserStats' : IDL.Func([], [IDL.Vec(UserStats)], ['query']),
    'register' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };