/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'background' : IDL.Text,
  'displayName' : IDL.Text,
  'color' : IDL.Text,
  'emoji' : IDL.Text,
});
export const Time = IDL.Int;
export const Entry = IDL.Record({
  'numberOfWipes' : IDL.Nat,
  'timestamp' : Time,
});
export const UserStats = IDL.Record({
  'principal' : IDL.Principal,
  'entries' : IDL.Vec(Entry),
  'totalToiletPaperRolls' : IDL.Nat,
  'avgWipesPerPoop' : IDL.Float64,
  'totalPoops' : IDL.Nat,
  'totalWipes' : IDL.Nat,
  'profile' : Profile,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPoopEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getRankedUserStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'today' : IDL.Vec(UserStats),
          'allTime' : IDL.Vec(UserStats),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([Profile], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'background' : IDL.Text,
    'displayName' : IDL.Text,
    'color' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const Time = IDL.Int;
  const Entry = IDL.Record({ 'numberOfWipes' : IDL.Nat, 'timestamp' : Time });
  const UserStats = IDL.Record({
    'principal' : IDL.Principal,
    'entries' : IDL.Vec(Entry),
    'totalToiletPaperRolls' : IDL.Nat,
    'avgWipesPerPoop' : IDL.Float64,
    'totalPoops' : IDL.Nat,
    'totalWipes' : IDL.Nat,
    'profile' : Profile,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPoopEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getRankedUserStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'today' : IDL.Vec(UserStats),
            'allTime' : IDL.Vec(UserStats),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([Profile], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };