/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry { 'numberOfWipes' : bigint, 'timestamp' : Time }
export interface Profile {
  'background' : string,
  'displayName' : string,
  'color' : string,
  'emoji' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'principal' : Principal,
  'entries' : Array<Entry>,
  'totalToiletPaperRolls' : bigint,
  'avgWipesPerPoop' : number,
  'totalPoops' : bigint,
  'totalWipes' : bigint,
  'profile' : Profile,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPoopEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyEntries' : ActorMethod<[], Array<Entry>>,
  'getRankedUserStats' : ActorMethod<
    [],
    { 'today' : Array<UserStats>, 'allTime' : Array<UserStats> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[Profile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];